/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseBreadcrumb: typeof import('./resources/ts/@core/components/BaseBreadcrumb.vue')['default']
    CardHeader: typeof import('./resources/ts/@core/components/CardHeader.vue')['default']
    CardHeaderFooter: typeof import('./resources/ts/@core/components/CardHeaderFooter.vue')['default']
    ComponentTitle: typeof import('./resources/ts/@core/components/ComponentTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgSprite: typeof import('./resources/ts/@core/components/SvgSprite.vue')['default']
    UiChildCard: typeof import('./resources/ts/@core/components/UiChildCard.vue')['default']
    UiParentCard: typeof import('./resources/ts/@core/components/UiParentCard.vue')['default']
    UiTableCard: typeof import('./resources/ts/@core/components/UiTableCard.vue')['default']
    UiTitleCard: typeof import('./resources/ts/@core/components/UiTitleCard.vue')['default']
    VueApexCharts: typeof import('vue3-apexcharts')['default']
    WidgetCard: typeof import('./resources/ts/@core/components/WidgetCard.vue')['default']
  }
}
