/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTypedList,
  RouteLocationAsPathTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  RouterLinkPropsTyped,
  NavigationGuard,
  UseLinkFnTyped,

  // data fetching
  _DataLoader,
  _DefineLoaderOptions,
} from 'unplugin-vue-router/types'

declare module 'vue-router/auto/routes' {
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'apps-calendar': RouteRecordInfo<'apps-calendar', '/apps/calendar', Record<never, never>, Record<never, never>>,
    'apps-chats': RouteRecordInfo<'apps-chats', '/apps/chats', Record<never, never>, Record<never, never>>,
    'apps-contacts-card': RouteRecordInfo<'apps-contacts-card', '/apps/contacts/card', Record<never, never>, Record<never, never>>,
    'apps-contacts-list': RouteRecordInfo<'apps-contacts-list', '/apps/contacts/list', Record<never, never>, Record<never, never>>,
    'apps-customer-create-invoice': RouteRecordInfo<'apps-customer-create-invoice', '/apps/customer/CreateInvoice', Record<never, never>, Record<never, never>>,
    'apps-customer-customer-list': RouteRecordInfo<'apps-customer-customer-list', '/apps/customer/CustomerList', Record<never, never>, Record<never, never>>,
    'apps-customer-orderdetails': RouteRecordInfo<'apps-customer-orderdetails', '/apps/customer/orderdetails', Record<never, never>, Record<never, never>>,
    'apps-customer-orderlist': RouteRecordInfo<'apps-customer-orderlist', '/apps/customer/orderlist', Record<never, never>, Record<never, never>>,
    'apps-customer-productlist': RouteRecordInfo<'apps-customer-productlist', '/apps/customer/productlist', Record<never, never>, Record<never, never>>,
    'apps-customer-productreview': RouteRecordInfo<'apps-customer-productreview', '/apps/customer/productreview', Record<never, never>, Record<never, never>>,
    'apps-ecommerce-addproduct': RouteRecordInfo<'apps-ecommerce-addproduct', '/apps/ecommerce/addproduct', Record<never, never>, Record<never, never>>,
    'apps-ecommerce-checkout': RouteRecordInfo<'apps-ecommerce-checkout', '/apps/ecommerce/checkout', Record<never, never>, Record<never, never>>,
    'apps-ecommerce-details': RouteRecordInfo<'apps-ecommerce-details', '/apps/ecommerce/details', Record<never, never>, Record<never, never>>,
    'apps-ecommerce-productlist': RouteRecordInfo<'apps-ecommerce-productlist', '/apps/ecommerce/productlist', Record<never, never>, Record<never, never>>,
    'apps-ecommerce-products': RouteRecordInfo<'apps-ecommerce-products', '/apps/ecommerce/products', Record<never, never>, Record<never, never>>,
    'apps-invoice-create': RouteRecordInfo<'apps-invoice-create', '/apps/invoice/create', Record<never, never>, Record<never, never>>,
    'apps-invoice-dashboard': RouteRecordInfo<'apps-invoice-dashboard', '/apps/invoice/dashboard', Record<never, never>, Record<never, never>>,
    'apps-invoice-details': RouteRecordInfo<'apps-invoice-details', '/apps/invoice/details', Record<never, never>, Record<never, never>>,
    'apps-invoice-edit': RouteRecordInfo<'apps-invoice-edit', '/apps/invoice/edit', Record<never, never>, Record<never, never>>,
    'apps-invoice-list': RouteRecordInfo<'apps-invoice-list', '/apps/invoice/list', Record<never, never>, Record<never, never>>,
    'apps-kanban': RouteRecordInfo<'apps-kanban', '/apps/kanban', Record<never, never>, Record<never, never>>,
    'apps-mail': RouteRecordInfo<'apps-mail', '/apps/mail', Record<never, never>, Record<never, never>>,
    'apps-users-accountprofile-profile1': RouteRecordInfo<'apps-users-accountprofile-profile1', '/apps/users/accountprofile/profile1', Record<never, never>, Record<never, never>>,
    'apps-users-accountprofile-profile2': RouteRecordInfo<'apps-users-accountprofile-profile2', '/apps/users/accountprofile/profile2', Record<never, never>, Record<never, never>>,
    'apps-users-accountprofile-profile3': RouteRecordInfo<'apps-users-accountprofile-profile3', '/apps/users/accountprofile/profile3', Record<never, never>, Record<never, never>>,
    'apps-users-card-card1': RouteRecordInfo<'apps-users-card-card1', '/apps/users/card/card1', Record<never, never>, Record<never, never>>,
    'apps-users-card-card2': RouteRecordInfo<'apps-users-card-card2', '/apps/users/card/card2', Record<never, never>, Record<never, never>>,
    'apps-users-card-card3': RouteRecordInfo<'apps-users-card-card3', '/apps/users/card/card3', Record<never, never>, Record<never, never>>,
    'apps-users-list-list1': RouteRecordInfo<'apps-users-list-list1', '/apps/users/list/list1', Record<never, never>, Record<never, never>>,
    'apps-users-list-list2': RouteRecordInfo<'apps-users-list-list2', '/apps/users/list/list2', Record<never, never>, Record<never, never>>,
    'apps-users-social-followers': RouteRecordInfo<'apps-users-social-followers', '/apps/users/social/followers', Record<never, never>, Record<never, never>>,
    'apps-users-social-friendrequest': RouteRecordInfo<'apps-users-social-friendrequest', '/apps/users/social/friendrequest', Record<never, never>, Record<never, never>>,
    'apps-users-social-friends': RouteRecordInfo<'apps-users-social-friends', '/apps/users/social/friends', Record<never, never>, Record<never, never>>,
    'apps-users-social-gallery': RouteRecordInfo<'apps-users-social-gallery', '/apps/users/social/gallery', Record<never, never>, Record<never, never>>,
    'apps-users-social-posts': RouteRecordInfo<'apps-users-social-posts', '/apps/users/social/posts', Record<never, never>, Record<never, never>>,
    'apps-users-userprofile': RouteRecordInfo<'apps-users-userprofile', '/apps/users/userprofile', Record<never, never>, Record<never, never>>,
    'authentication-auth1-check-mail1': RouteRecordInfo<'authentication-auth1-check-mail1', '/authentication/auth1/CheckMail1', Record<never, never>, Record<never, never>>,
    'authentication-auth1-code-verification1': RouteRecordInfo<'authentication-auth1-code-verification1', '/authentication/auth1/CodeVerification1', Record<never, never>, Record<never, never>>,
    'authentication-auth1-forgot-pwd1': RouteRecordInfo<'authentication-auth1-forgot-pwd1', '/authentication/auth1/ForgotPwd1', Record<never, never>, Record<never, never>>,
    'authentication-auth1-login1': RouteRecordInfo<'authentication-auth1-login1', '/authentication/auth1/login1', Record<never, never>, Record<never, never>>,
    'authentication-auth1-register1': RouteRecordInfo<'authentication-auth1-register1', '/authentication/auth1/register1', Record<never, never>, Record<never, never>>,
    'authentication-auth1-reset-pwd1': RouteRecordInfo<'authentication-auth1-reset-pwd1', '/authentication/auth1/ResetPwd1', Record<never, never>, Record<never, never>>,
    'authentication-auth2-check-mail2': RouteRecordInfo<'authentication-auth2-check-mail2', '/authentication/auth2/CheckMail2', Record<never, never>, Record<never, never>>,
    'authentication-auth2-code-verification2': RouteRecordInfo<'authentication-auth2-code-verification2', '/authentication/auth2/CodeVerification2', Record<never, never>, Record<never, never>>,
    'authentication-auth2-forgot-pwd2': RouteRecordInfo<'authentication-auth2-forgot-pwd2', '/authentication/auth2/ForgotPwd2', Record<never, never>, Record<never, never>>,
    'authentication-auth2-login2': RouteRecordInfo<'authentication-auth2-login2', '/authentication/auth2/login2', Record<never, never>, Record<never, never>>,
    'authentication-auth2-register2': RouteRecordInfo<'authentication-auth2-register2', '/authentication/auth2/register2', Record<never, never>, Record<never, never>>,
    'authentication-auth2-reset-pwd2': RouteRecordInfo<'authentication-auth2-reset-pwd2', '/authentication/auth2/ResetPwd2', Record<never, never>, Record<never, never>>,
    'authentication-auth3': RouteRecordInfo<'authentication-auth3', '/authentication/auth3', Record<never, never>, Record<never, never>>,
    'contactus': RouteRecordInfo<'contactus', '/contactus', Record<never, never>, Record<never, never>>,
    'dashboards-analytics': RouteRecordInfo<'dashboards-analytics', '/dashboards/analytics', Record<never, never>, Record<never, never>>,
    'dashboards-default': RouteRecordInfo<'dashboards-default', '/dashboards/default', Record<never, never>, Record<never, never>>,
    'documentos': RouteRecordInfo<'documentos', '/documentos', Record<never, never>, Record<never, never>>,
    'documentos-atributos': RouteRecordInfo<'documentos-atributos', '/documentos/atributos', Record<never, never>, Record<never, never>>,
    'documentos-documentos': RouteRecordInfo<'documentos-documentos', '/documentos/documentos', Record<never, never>, Record<never, never>>,
    'documentos-layout': RouteRecordInfo<'documentos-layout', '/documentos/layout', Record<never, never>, Record<never, never>>,
    'documentos-relatorio-layout': RouteRecordInfo<'documentos-relatorio-layout', '/documentos/relatorio-layout', Record<never, never>, Record<never, never>>,
    'documentos-relatorios': RouteRecordInfo<'documentos-relatorios', '/documentos/relatorios', Record<never, never>, Record<never, never>>,
    'documentos-secoes': RouteRecordInfo<'documentos-secoes', '/documentos/secoes', Record<never, never>, Record<never, never>>,
    'documentos-tipos': RouteRecordInfo<'documentos-tipos', '/documentos/tipos', Record<never, never>, Record<never, never>>,
    'error500': RouteRecordInfo<'error500', '/error500', Record<never, never>, Record<never, never>>,
    'faq': RouteRecordInfo<'faq', '/faq', Record<never, never>, Record<never, never>>,
    'forms-charts-apex-chart': RouteRecordInfo<'forms-charts-apex-chart', '/forms/charts/ApexChart', Record<never, never>, Record<never, never>>,
    'forms-charts-orgchart': RouteRecordInfo<'forms-charts-orgchart', '/forms/charts/orgchart', Record<never, never>, Record<never, never>>,
    'forms-components-autocomplete': RouteRecordInfo<'forms-components-autocomplete', '/forms/components/autocomplete', Record<never, never>, Record<never, never>>,
    'forms-components-buttons': RouteRecordInfo<'forms-components-buttons', '/forms/components/buttons', Record<never, never>, Record<never, never>>,
    'forms-components-checkbox': RouteRecordInfo<'forms-components-checkbox', '/forms/components/checkbox', Record<never, never>, Record<never, never>>,
    'forms-components-radio': RouteRecordInfo<'forms-components-radio', '/forms/components/radio', Record<never, never>, Record<never, never>>,
    'forms-components-slider': RouteRecordInfo<'forms-components-slider', '/forms/components/slider', Record<never, never>, Record<never, never>>,
    'forms-components-switch': RouteRecordInfo<'forms-components-switch', '/forms/components/switch', Record<never, never>, Record<never, never>>,
    'forms-components-textfield': RouteRecordInfo<'forms-components-textfield', '/forms/components/textfield', Record<never, never>, Record<never, never>>,
    'forms-form-validation': RouteRecordInfo<'forms-form-validation', '/forms/FormValidation', Record<never, never>, Record<never, never>>,
    'forms-layouts-action-bar': RouteRecordInfo<'forms-layouts-action-bar', '/forms/layouts/ActionBar', Record<never, never>, Record<never, never>>,
    'forms-layouts-layouts': RouteRecordInfo<'forms-layouts-layouts', '/forms/layouts/layouts', Record<never, never>, Record<never, never>>,
    'forms-layouts-multi-column-forms': RouteRecordInfo<'forms-layouts-multi-column-forms', '/forms/layouts/MultiColumnForms', Record<never, never>, Record<never, never>>,
    'forms-layouts-sticky-action-bar': RouteRecordInfo<'forms-layouts-sticky-action-bar', '/forms/layouts/StickyActionBar', Record<never, never>, Record<never, never>>,
    'forms-plugins-captcha': RouteRecordInfo<'forms-plugins-captcha', '/forms/plugins/captcha', Record<never, never>, Record<never, never>>,
    'forms-plugins-clipboard': RouteRecordInfo<'forms-plugins-clipboard', '/forms/plugins/clipboard', Record<never, never>, Record<never, never>>,
    'forms-plugins-dialog': RouteRecordInfo<'forms-plugins-dialog', '/forms/plugins/dialog', Record<never, never>, Record<never, never>>,
    'forms-plugins-dropzone': RouteRecordInfo<'forms-plugins-dropzone', '/forms/plugins/dropzone', Record<never, never>, Record<never, never>>,
    'forms-plugins-editor': RouteRecordInfo<'forms-plugins-editor', '/forms/plugins/editor', Record<never, never>, Record<never, never>>,
    'forms-plugins-mask': RouteRecordInfo<'forms-plugins-mask', '/forms/plugins/mask', Record<never, never>, Record<never, never>>,
    'forms-plugins-tooltip': RouteRecordInfo<'forms-plugins-tooltip', '/forms/plugins/tooltip', Record<never, never>, Record<never, never>>,
    'forms-tables-table-basic': RouteRecordInfo<'forms-tables-table-basic', '/forms/tables/TableBasic', Record<never, never>, Record<never, never>>,
    'forms-tables-table-dark': RouteRecordInfo<'forms-tables-table-dark', '/forms/tables/TableDark', Record<never, never>, Record<never, never>>,
    'forms-tables-table-density': RouteRecordInfo<'forms-tables-table-density', '/forms/tables/TableDensity', Record<never, never>, Record<never, never>>,
    'forms-tables-table-header-fixed': RouteRecordInfo<'forms-tables-table-header-fixed', '/forms/tables/TableHeaderFixed', Record<never, never>, Record<never, never>>,
    'forms-tables-table-height': RouteRecordInfo<'forms-tables-table-height', '/forms/tables/TableHeight', Record<never, never>, Record<never, never>>,
    'landing': RouteRecordInfo<'landing', '/landing', Record<never, never>, Record<never, never>>,
    'maintenance-comingsoon1': RouteRecordInfo<'maintenance-comingsoon1', '/maintenance/comingsoon1', Record<never, never>, Record<never, never>>,
    'maintenance-comingsoon2': RouteRecordInfo<'maintenance-comingsoon2', '/maintenance/comingsoon2', Record<never, never>, Record<never, never>>,
    'pricing-pricing1': RouteRecordInfo<'pricing-pricing1', '/pricing/pricing1', Record<never, never>, Record<never, never>>,
    'pricing-pricing2': RouteRecordInfo<'pricing-pricing2', '/pricing/pricing2', Record<never, never>, Record<never, never>>,
    'privacypolicy': RouteRecordInfo<'privacypolicy', '/privacypolicy', Record<never, never>, Record<never, never>>,
    'starter': RouteRecordInfo<'starter', '/starter', Record<never, never>, Record<never, never>>,
    'ui-elements-advance-alert': RouteRecordInfo<'ui-elements-advance-alert', '/ui-elements/advance/alert', Record<never, never>, Record<never, never>>,
    'ui-elements-advance-buttontoggle': RouteRecordInfo<'ui-elements-advance-buttontoggle', '/ui-elements/advance/buttontoggle', Record<never, never>, Record<never, never>>,
    'ui-elements-advance-emptystate': RouteRecordInfo<'ui-elements-advance-emptystate', '/ui-elements/advance/emptystate', Record<never, never>, Record<never, never>>,
    'ui-elements-advance-floatingaction': RouteRecordInfo<'ui-elements-advance-floatingaction', '/ui-elements/advance/floatingaction', Record<never, never>, Record<never, never>>,
    'ui-elements-advance-pagination': RouteRecordInfo<'ui-elements-advance-pagination', '/ui-elements/advance/pagination', Record<never, never>, Record<never, never>>,
    'ui-elements-advance-progress': RouteRecordInfo<'ui-elements-advance-progress', '/ui-elements/advance/progress', Record<never, never>, Record<never, never>>,
    'ui-elements-advance-ratings': RouteRecordInfo<'ui-elements-advance-ratings', '/ui-elements/advance/ratings', Record<never, never>, Record<never, never>>,
    'ui-elements-advance-snackbar': RouteRecordInfo<'ui-elements-advance-snackbar', '/ui-elements/advance/snackbar', Record<never, never>, Record<never, never>>,
    'ui-elements-advance-speeddial': RouteRecordInfo<'ui-elements-advance-speeddial', '/ui-elements/advance/speeddial', Record<never, never>, Record<never, never>>,
    'ui-elements-advance-timeline': RouteRecordInfo<'ui-elements-advance-timeline', '/ui-elements/advance/timeline', Record<never, never>, Record<never, never>>,
    'ui-elements-basic-avatar': RouteRecordInfo<'ui-elements-basic-avatar', '/ui-elements/basic/avatar', Record<never, never>, Record<never, never>>,
    'ui-elements-basic-badges': RouteRecordInfo<'ui-elements-basic-badges', '/ui-elements/basic/badges', Record<never, never>, Record<never, never>>,
    'ui-elements-basic-breadcrumb': RouteRecordInfo<'ui-elements-basic-breadcrumb', '/ui-elements/basic/breadcrumb', Record<never, never>, Record<never, never>>,
    'ui-elements-basic-cards': RouteRecordInfo<'ui-elements-basic-cards', '/ui-elements/basic/cards', Record<never, never>, Record<never, never>>,
    'ui-elements-basic-chip': RouteRecordInfo<'ui-elements-basic-chip', '/ui-elements/basic/chip', Record<never, never>, Record<never, never>>,
    'ui-elements-basic-expansionpanel': RouteRecordInfo<'ui-elements-basic-expansionpanel', '/ui-elements/basic/expansionpanel', Record<never, never>, Record<never, never>>,
    'ui-elements-basic-tabs': RouteRecordInfo<'ui-elements-basic-tabs', '/ui-elements/basic/tabs', Record<never, never>, Record<never, never>>,
    'ui-elements-basic-ui-list': RouteRecordInfo<'ui-elements-basic-ui-list', '/ui-elements/basic/UiList', Record<never, never>, Record<never, never>>,
    'underconstruction-construction1': RouteRecordInfo<'underconstruction-construction1', '/underconstruction/construction1', Record<never, never>, Record<never, never>>,
    'underconstruction-construction2': RouteRecordInfo<'underconstruction-construction2', '/underconstruction/construction2', Record<never, never>, Record<never, never>>,
    'utilities-animation': RouteRecordInfo<'utilities-animation', '/utilities/animation', Record<never, never>, Record<never, never>>,
    'utilities-colors': RouteRecordInfo<'utilities-colors', '/utilities/colors', Record<never, never>, Record<never, never>>,
    'utilities-grid': RouteRecordInfo<'utilities-grid', '/utilities/grid', Record<never, never>, Record<never, never>>,
    'utilities-icons-material': RouteRecordInfo<'utilities-icons-material', '/utilities/icons/material', Record<never, never>, Record<never, never>>,
    'utilities-icons-tabler': RouteRecordInfo<'utilities-icons-tabler', '/utilities/icons/tabler', Record<never, never>, Record<never, never>>,
    'utilities-shadows': RouteRecordInfo<'utilities-shadows', '/utilities/shadows', Record<never, never>, Record<never, never>>,
    'utilities-typography': RouteRecordInfo<'utilities-typography', '/utilities/typography', Record<never, never>, Record<never, never>>,
    'widgets-chart': RouteRecordInfo<'widgets-chart', '/widgets/chart', Record<never, never>, Record<never, never>>,
    'widgets-data': RouteRecordInfo<'widgets-data', '/widgets/data', Record<never, never>, Record<never, never>>,
    'widgets-statistics': RouteRecordInfo<'widgets-statistics', '/widgets/statistics', Record<never, never>, Record<never, never>>,
  }
}

declare module 'vue-router/auto' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationRaw<Name extends keyof RouteNamedMap = keyof RouteNamedMap> =
    | RouteLocationAsString<RouteNamedMap>
    | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
    | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

  export function useRouter(): RouterTyped
  export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
  export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void

  export const RouterLink: RouterLinkTyped<RouteNamedMap>
  export const RouterLinkProps: RouterLinkPropsTyped<RouteNamedMap>

  // Experimental Data Fetching

  export function defineLoader<
    P extends Promise<any>,
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
    isLazy extends boolean = false,
  >(
    name: Name,
    loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>
  export function defineLoader<
    P extends Promise<any>,
    isLazy extends boolean = false,
  >(
    loader: (route: RouteLocationNormalizedLoaded) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>

  export {
    _definePage as definePage,
    _HasDataLoaderMeta as HasDataLoaderMeta,
    _setupDataFetchingGuard as setupDataFetchingGuard,
    _stopDataFetchingScope as stopDataFetchingScope,
  } from 'unplugin-vue-router/runtime'
}

declare module 'vue-router' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
