/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/[...error]': RouteRecordInfo<'/[...error]', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    '/apps/calendar': RouteRecordInfo<'/apps/calendar', '/apps/calendar', Record<never, never>, Record<never, never>>,
    '/apps/chats': RouteRecordInfo<'/apps/chats', '/apps/chats', Record<never, never>, Record<never, never>>,
    '/apps/contacts/card': RouteRecordInfo<'/apps/contacts/card', '/apps/contacts/card', Record<never, never>, Record<never, never>>,
    '/apps/contacts/list': RouteRecordInfo<'/apps/contacts/list', '/apps/contacts/list', Record<never, never>, Record<never, never>>,
    '/apps/customer/CreateInvoice': RouteRecordInfo<'/apps/customer/CreateInvoice', '/apps/customer/CreateInvoice', Record<never, never>, Record<never, never>>,
    '/apps/customer/CustomerList': RouteRecordInfo<'/apps/customer/CustomerList', '/apps/customer/CustomerList', Record<never, never>, Record<never, never>>,
    '/apps/customer/orderdetails': RouteRecordInfo<'/apps/customer/orderdetails', '/apps/customer/orderdetails', Record<never, never>, Record<never, never>>,
    '/apps/customer/orderlist': RouteRecordInfo<'/apps/customer/orderlist', '/apps/customer/orderlist', Record<never, never>, Record<never, never>>,
    '/apps/customer/productlist': RouteRecordInfo<'/apps/customer/productlist', '/apps/customer/productlist', Record<never, never>, Record<never, never>>,
    '/apps/customer/productreview': RouteRecordInfo<'/apps/customer/productreview', '/apps/customer/productreview', Record<never, never>, Record<never, never>>,
    '/apps/ecommerce/addproduct': RouteRecordInfo<'/apps/ecommerce/addproduct', '/apps/ecommerce/addproduct', Record<never, never>, Record<never, never>>,
    '/apps/ecommerce/checkout': RouteRecordInfo<'/apps/ecommerce/checkout', '/apps/ecommerce/checkout', Record<never, never>, Record<never, never>>,
    '/apps/ecommerce/details/': RouteRecordInfo<'/apps/ecommerce/details/', '/apps/ecommerce/details', Record<never, never>, Record<never, never>>,
    '/apps/ecommerce/productlist': RouteRecordInfo<'/apps/ecommerce/productlist', '/apps/ecommerce/productlist', Record<never, never>, Record<never, never>>,
    '/apps/ecommerce/products': RouteRecordInfo<'/apps/ecommerce/products', '/apps/ecommerce/products', Record<never, never>, Record<never, never>>,
    '/apps/invoice/create': RouteRecordInfo<'/apps/invoice/create', '/apps/invoice/create', Record<never, never>, Record<never, never>>,
    '/apps/invoice/dashboard': RouteRecordInfo<'/apps/invoice/dashboard', '/apps/invoice/dashboard', Record<never, never>, Record<never, never>>,
    '/apps/invoice/details': RouteRecordInfo<'/apps/invoice/details', '/apps/invoice/details', Record<never, never>, Record<never, never>>,
    '/apps/invoice/edit': RouteRecordInfo<'/apps/invoice/edit', '/apps/invoice/edit', Record<never, never>, Record<never, never>>,
    '/apps/invoice/list': RouteRecordInfo<'/apps/invoice/list', '/apps/invoice/list', Record<never, never>, Record<never, never>>,
    '/apps/kanban': RouteRecordInfo<'/apps/kanban', '/apps/kanban', Record<never, never>, Record<never, never>>,
    '/apps/mail': RouteRecordInfo<'/apps/mail', '/apps/mail', Record<never, never>, Record<never, never>>,
    '/apps/users/accountprofile/profile1': RouteRecordInfo<'/apps/users/accountprofile/profile1', '/apps/users/accountprofile/profile1', Record<never, never>, Record<never, never>>,
    '/apps/users/accountprofile/profile2': RouteRecordInfo<'/apps/users/accountprofile/profile2', '/apps/users/accountprofile/profile2', Record<never, never>, Record<never, never>>,
    '/apps/users/accountprofile/profile3': RouteRecordInfo<'/apps/users/accountprofile/profile3', '/apps/users/accountprofile/profile3', Record<never, never>, Record<never, never>>,
    '/apps/users/card/card1': RouteRecordInfo<'/apps/users/card/card1', '/apps/users/card/card1', Record<never, never>, Record<never, never>>,
    '/apps/users/card/card2': RouteRecordInfo<'/apps/users/card/card2', '/apps/users/card/card2', Record<never, never>, Record<never, never>>,
    '/apps/users/card/card3': RouteRecordInfo<'/apps/users/card/card3', '/apps/users/card/card3', Record<never, never>, Record<never, never>>,
    '/apps/users/list/list1': RouteRecordInfo<'/apps/users/list/list1', '/apps/users/list/list1', Record<never, never>, Record<never, never>>,
    '/apps/users/list/list2': RouteRecordInfo<'/apps/users/list/list2', '/apps/users/list/list2', Record<never, never>, Record<never, never>>,
    '/apps/users/social/followers': RouteRecordInfo<'/apps/users/social/followers', '/apps/users/social/followers', Record<never, never>, Record<never, never>>,
    '/apps/users/social/friendrequest': RouteRecordInfo<'/apps/users/social/friendrequest', '/apps/users/social/friendrequest', Record<never, never>, Record<never, never>>,
    '/apps/users/social/friends': RouteRecordInfo<'/apps/users/social/friends', '/apps/users/social/friends', Record<never, never>, Record<never, never>>,
    '/apps/users/social/gallery': RouteRecordInfo<'/apps/users/social/gallery', '/apps/users/social/gallery', Record<never, never>, Record<never, never>>,
    '/apps/users/social/posts': RouteRecordInfo<'/apps/users/social/posts', '/apps/users/social/posts', Record<never, never>, Record<never, never>>,
    '/apps/users/userprofile': RouteRecordInfo<'/apps/users/userprofile', '/apps/users/userprofile', Record<never, never>, Record<never, never>>,
    '/authentication/auth1/CheckMail1': RouteRecordInfo<'/authentication/auth1/CheckMail1', '/authentication/auth1/CheckMail1', Record<never, never>, Record<never, never>>,
    '/authentication/auth1/CodeVerification1': RouteRecordInfo<'/authentication/auth1/CodeVerification1', '/authentication/auth1/CodeVerification1', Record<never, never>, Record<never, never>>,
    '/authentication/auth1/ForgotPwd1': RouteRecordInfo<'/authentication/auth1/ForgotPwd1', '/authentication/auth1/ForgotPwd1', Record<never, never>, Record<never, never>>,
    '/authentication/auth1/login1': RouteRecordInfo<'/authentication/auth1/login1', '/authentication/auth1/login1', Record<never, never>, Record<never, never>>,
    '/authentication/auth1/register1': RouteRecordInfo<'/authentication/auth1/register1', '/authentication/auth1/register1', Record<never, never>, Record<never, never>>,
    '/authentication/auth1/ResetPwd1': RouteRecordInfo<'/authentication/auth1/ResetPwd1', '/authentication/auth1/ResetPwd1', Record<never, never>, Record<never, never>>,
    '/authentication/auth2/CheckMail2': RouteRecordInfo<'/authentication/auth2/CheckMail2', '/authentication/auth2/CheckMail2', Record<never, never>, Record<never, never>>,
    '/authentication/auth2/CodeVerification2': RouteRecordInfo<'/authentication/auth2/CodeVerification2', '/authentication/auth2/CodeVerification2', Record<never, never>, Record<never, never>>,
    '/authentication/auth2/ForgotPwd2': RouteRecordInfo<'/authentication/auth2/ForgotPwd2', '/authentication/auth2/ForgotPwd2', Record<never, never>, Record<never, never>>,
    '/authentication/auth2/login2': RouteRecordInfo<'/authentication/auth2/login2', '/authentication/auth2/login2', Record<never, never>, Record<never, never>>,
    '/authentication/auth2/register2': RouteRecordInfo<'/authentication/auth2/register2', '/authentication/auth2/register2', Record<never, never>, Record<never, never>>,
    '/authentication/auth2/ResetPwd2': RouteRecordInfo<'/authentication/auth2/ResetPwd2', '/authentication/auth2/ResetPwd2', Record<never, never>, Record<never, never>>,
    '/authentication/auth3': RouteRecordInfo<'/authentication/auth3', '/authentication/auth3', Record<never, never>, Record<never, never>>,
    '/contactus': RouteRecordInfo<'/contactus', '/contactus', Record<never, never>, Record<never, never>>,
    '/dashboards/analytics': RouteRecordInfo<'/dashboards/analytics', '/dashboards/analytics', Record<never, never>, Record<never, never>>,
    '/dashboards/default': RouteRecordInfo<'/dashboards/default', '/dashboards/default', Record<never, never>, Record<never, never>>,
    '/documentos/': RouteRecordInfo<'/documentos/', '/documentos', Record<never, never>, Record<never, never>>,
    '/documentos/atributos': RouteRecordInfo<'/documentos/atributos', '/documentos/atributos', Record<never, never>, Record<never, never>>,
    '/documentos/documentos': RouteRecordInfo<'/documentos/documentos', '/documentos/documentos', Record<never, never>, Record<never, never>>,
    '/documentos/layout': RouteRecordInfo<'/documentos/layout', '/documentos/layout', Record<never, never>, Record<never, never>>,
    '/documentos/relatorio-layout': RouteRecordInfo<'/documentos/relatorio-layout', '/documentos/relatorio-layout', Record<never, never>, Record<never, never>>,
    '/documentos/relatorios': RouteRecordInfo<'/documentos/relatorios', '/documentos/relatorios', Record<never, never>, Record<never, never>>,
    '/documentos/secoes': RouteRecordInfo<'/documentos/secoes', '/documentos/secoes', Record<never, never>, Record<never, never>>,
    '/documentos/tipos': RouteRecordInfo<'/documentos/tipos', '/documentos/tipos', Record<never, never>, Record<never, never>>,
    '/error500': RouteRecordInfo<'/error500', '/error500', Record<never, never>, Record<never, never>>,
    '/faq': RouteRecordInfo<'/faq', '/faq', Record<never, never>, Record<never, never>>,
    '/forms/charts/ApexChart': RouteRecordInfo<'/forms/charts/ApexChart', '/forms/charts/ApexChart', Record<never, never>, Record<never, never>>,
    '/forms/charts/orgchart': RouteRecordInfo<'/forms/charts/orgchart', '/forms/charts/orgchart', Record<never, never>, Record<never, never>>,
    '/forms/components/autocomplete': RouteRecordInfo<'/forms/components/autocomplete', '/forms/components/autocomplete', Record<never, never>, Record<never, never>>,
    '/forms/components/buttons': RouteRecordInfo<'/forms/components/buttons', '/forms/components/buttons', Record<never, never>, Record<never, never>>,
    '/forms/components/checkbox': RouteRecordInfo<'/forms/components/checkbox', '/forms/components/checkbox', Record<never, never>, Record<never, never>>,
    '/forms/components/radio': RouteRecordInfo<'/forms/components/radio', '/forms/components/radio', Record<never, never>, Record<never, never>>,
    '/forms/components/slider': RouteRecordInfo<'/forms/components/slider', '/forms/components/slider', Record<never, never>, Record<never, never>>,
    '/forms/components/switch': RouteRecordInfo<'/forms/components/switch', '/forms/components/switch', Record<never, never>, Record<never, never>>,
    '/forms/components/textfield': RouteRecordInfo<'/forms/components/textfield', '/forms/components/textfield', Record<never, never>, Record<never, never>>,
    '/forms/FormValidation': RouteRecordInfo<'/forms/FormValidation', '/forms/FormValidation', Record<never, never>, Record<never, never>>,
    '/forms/layouts/ActionBar': RouteRecordInfo<'/forms/layouts/ActionBar', '/forms/layouts/ActionBar', Record<never, never>, Record<never, never>>,
    '/forms/layouts/layouts': RouteRecordInfo<'/forms/layouts/layouts', '/forms/layouts/layouts', Record<never, never>, Record<never, never>>,
    '/forms/layouts/MultiColumnForms': RouteRecordInfo<'/forms/layouts/MultiColumnForms', '/forms/layouts/MultiColumnForms', Record<never, never>, Record<never, never>>,
    '/forms/layouts/StickyActionBar': RouteRecordInfo<'/forms/layouts/StickyActionBar', '/forms/layouts/StickyActionBar', Record<never, never>, Record<never, never>>,
    '/forms/plugins/captcha': RouteRecordInfo<'/forms/plugins/captcha', '/forms/plugins/captcha', Record<never, never>, Record<never, never>>,
    '/forms/plugins/clipboard': RouteRecordInfo<'/forms/plugins/clipboard', '/forms/plugins/clipboard', Record<never, never>, Record<never, never>>,
    '/forms/plugins/dialog': RouteRecordInfo<'/forms/plugins/dialog', '/forms/plugins/dialog', Record<never, never>, Record<never, never>>,
    '/forms/plugins/dropzone': RouteRecordInfo<'/forms/plugins/dropzone', '/forms/plugins/dropzone', Record<never, never>, Record<never, never>>,
    '/forms/plugins/editor': RouteRecordInfo<'/forms/plugins/editor', '/forms/plugins/editor', Record<never, never>, Record<never, never>>,
    '/forms/plugins/mask': RouteRecordInfo<'/forms/plugins/mask', '/forms/plugins/mask', Record<never, never>, Record<never, never>>,
    '/forms/plugins/tooltip': RouteRecordInfo<'/forms/plugins/tooltip', '/forms/plugins/tooltip', Record<never, never>, Record<never, never>>,
    '/forms/tables/TableBasic': RouteRecordInfo<'/forms/tables/TableBasic', '/forms/tables/TableBasic', Record<never, never>, Record<never, never>>,
    '/forms/tables/TableDark': RouteRecordInfo<'/forms/tables/TableDark', '/forms/tables/TableDark', Record<never, never>, Record<never, never>>,
    '/forms/tables/TableDensity': RouteRecordInfo<'/forms/tables/TableDensity', '/forms/tables/TableDensity', Record<never, never>, Record<never, never>>,
    '/forms/tables/TableHeaderFixed': RouteRecordInfo<'/forms/tables/TableHeaderFixed', '/forms/tables/TableHeaderFixed', Record<never, never>, Record<never, never>>,
    '/forms/tables/TableHeight': RouteRecordInfo<'/forms/tables/TableHeight', '/forms/tables/TableHeight', Record<never, never>, Record<never, never>>,
    '/landing': RouteRecordInfo<'/landing', '/landing', Record<never, never>, Record<never, never>>,
    '/maintenance/comingsoon1': RouteRecordInfo<'/maintenance/comingsoon1', '/maintenance/comingsoon1', Record<never, never>, Record<never, never>>,
    '/maintenance/comingsoon2': RouteRecordInfo<'/maintenance/comingsoon2', '/maintenance/comingsoon2', Record<never, never>, Record<never, never>>,
    '/pricing/pricing1': RouteRecordInfo<'/pricing/pricing1', '/pricing/pricing1', Record<never, never>, Record<never, never>>,
    '/pricing/pricing2': RouteRecordInfo<'/pricing/pricing2', '/pricing/pricing2', Record<never, never>, Record<never, never>>,
    '/privacypolicy': RouteRecordInfo<'/privacypolicy', '/privacypolicy', Record<never, never>, Record<never, never>>,
    '/starter': RouteRecordInfo<'/starter', '/starter', Record<never, never>, Record<never, never>>,
    '/ui-elements/advance/alert': RouteRecordInfo<'/ui-elements/advance/alert', '/ui-elements/advance/alert', Record<never, never>, Record<never, never>>,
    '/ui-elements/advance/buttontoggle': RouteRecordInfo<'/ui-elements/advance/buttontoggle', '/ui-elements/advance/buttontoggle', Record<never, never>, Record<never, never>>,
    '/ui-elements/advance/emptystate': RouteRecordInfo<'/ui-elements/advance/emptystate', '/ui-elements/advance/emptystate', Record<never, never>, Record<never, never>>,
    '/ui-elements/advance/floatingaction': RouteRecordInfo<'/ui-elements/advance/floatingaction', '/ui-elements/advance/floatingaction', Record<never, never>, Record<never, never>>,
    '/ui-elements/advance/pagination': RouteRecordInfo<'/ui-elements/advance/pagination', '/ui-elements/advance/pagination', Record<never, never>, Record<never, never>>,
    '/ui-elements/advance/progress': RouteRecordInfo<'/ui-elements/advance/progress', '/ui-elements/advance/progress', Record<never, never>, Record<never, never>>,
    '/ui-elements/advance/ratings': RouteRecordInfo<'/ui-elements/advance/ratings', '/ui-elements/advance/ratings', Record<never, never>, Record<never, never>>,
    '/ui-elements/advance/snackbar': RouteRecordInfo<'/ui-elements/advance/snackbar', '/ui-elements/advance/snackbar', Record<never, never>, Record<never, never>>,
    '/ui-elements/advance/speeddial': RouteRecordInfo<'/ui-elements/advance/speeddial', '/ui-elements/advance/speeddial', Record<never, never>, Record<never, never>>,
    '/ui-elements/advance/timeline': RouteRecordInfo<'/ui-elements/advance/timeline', '/ui-elements/advance/timeline', Record<never, never>, Record<never, never>>,
    '/ui-elements/basic/avatar': RouteRecordInfo<'/ui-elements/basic/avatar', '/ui-elements/basic/avatar', Record<never, never>, Record<never, never>>,
    '/ui-elements/basic/badges': RouteRecordInfo<'/ui-elements/basic/badges', '/ui-elements/basic/badges', Record<never, never>, Record<never, never>>,
    '/ui-elements/basic/breadcrumb': RouteRecordInfo<'/ui-elements/basic/breadcrumb', '/ui-elements/basic/breadcrumb', Record<never, never>, Record<never, never>>,
    '/ui-elements/basic/cards': RouteRecordInfo<'/ui-elements/basic/cards', '/ui-elements/basic/cards', Record<never, never>, Record<never, never>>,
    '/ui-elements/basic/chip': RouteRecordInfo<'/ui-elements/basic/chip', '/ui-elements/basic/chip', Record<never, never>, Record<never, never>>,
    '/ui-elements/basic/expansionpanel': RouteRecordInfo<'/ui-elements/basic/expansionpanel', '/ui-elements/basic/expansionpanel', Record<never, never>, Record<never, never>>,
    '/ui-elements/basic/tabs': RouteRecordInfo<'/ui-elements/basic/tabs', '/ui-elements/basic/tabs', Record<never, never>, Record<never, never>>,
    '/ui-elements/basic/UiList': RouteRecordInfo<'/ui-elements/basic/UiList', '/ui-elements/basic/UiList', Record<never, never>, Record<never, never>>,
    '/underconstruction/construction1': RouteRecordInfo<'/underconstruction/construction1', '/underconstruction/construction1', Record<never, never>, Record<never, never>>,
    '/underconstruction/construction2': RouteRecordInfo<'/underconstruction/construction2', '/underconstruction/construction2', Record<never, never>, Record<never, never>>,
    '/utilities/animation': RouteRecordInfo<'/utilities/animation', '/utilities/animation', Record<never, never>, Record<never, never>>,
    '/utilities/colors': RouteRecordInfo<'/utilities/colors', '/utilities/colors', Record<never, never>, Record<never, never>>,
    '/utilities/grid': RouteRecordInfo<'/utilities/grid', '/utilities/grid', Record<never, never>, Record<never, never>>,
    '/utilities/icons/material': RouteRecordInfo<'/utilities/icons/material', '/utilities/icons/material', Record<never, never>, Record<never, never>>,
    '/utilities/icons/tabler': RouteRecordInfo<'/utilities/icons/tabler', '/utilities/icons/tabler', Record<never, never>, Record<never, never>>,
    '/utilities/shadows': RouteRecordInfo<'/utilities/shadows', '/utilities/shadows', Record<never, never>, Record<never, never>>,
    '/utilities/typography': RouteRecordInfo<'/utilities/typography', '/utilities/typography', Record<never, never>, Record<never, never>>,
    '/widgets/chart': RouteRecordInfo<'/widgets/chart', '/widgets/chart', Record<never, never>, Record<never, never>>,
    '/widgets/data': RouteRecordInfo<'/widgets/data', '/widgets/data', Record<never, never>, Record<never, never>>,
    '/widgets/statistics': RouteRecordInfo<'/widgets/statistics', '/widgets/statistics', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'resources/ts/pages/[...error].vue': {
      routes: '/[...error]'
      views: never
    }
    'resources/ts/pages/apps/calendar.vue': {
      routes: '/apps/calendar'
      views: never
    }
    'resources/ts/pages/apps/chats.vue': {
      routes: '/apps/chats'
      views: never
    }
    'resources/ts/pages/apps/contacts/card.vue': {
      routes: '/apps/contacts/card'
      views: never
    }
    'resources/ts/pages/apps/contacts/list.vue': {
      routes: '/apps/contacts/list'
      views: never
    }
    'resources/ts/pages/apps/customer/CreateInvoice.vue': {
      routes: '/apps/customer/CreateInvoice'
      views: never
    }
    'resources/ts/pages/apps/customer/CustomerList.vue': {
      routes: '/apps/customer/CustomerList'
      views: never
    }
    'resources/ts/pages/apps/customer/orderdetails.vue': {
      routes: '/apps/customer/orderdetails'
      views: never
    }
    'resources/ts/pages/apps/customer/orderlist.vue': {
      routes: '/apps/customer/orderlist'
      views: never
    }
    'resources/ts/pages/apps/customer/productlist.vue': {
      routes: '/apps/customer/productlist'
      views: never
    }
    'resources/ts/pages/apps/customer/productreview.vue': {
      routes: '/apps/customer/productreview'
      views: never
    }
    'resources/ts/pages/apps/ecommerce/addproduct.vue': {
      routes: '/apps/ecommerce/addproduct'
      views: never
    }
    'resources/ts/pages/apps/ecommerce/checkout.vue': {
      routes: '/apps/ecommerce/checkout'
      views: never
    }
    'resources/ts/pages/apps/ecommerce/details/index.vue': {
      routes: '/apps/ecommerce/details/'
      views: never
    }
    'resources/ts/pages/apps/ecommerce/productlist.vue': {
      routes: '/apps/ecommerce/productlist'
      views: never
    }
    'resources/ts/pages/apps/ecommerce/products.vue': {
      routes: '/apps/ecommerce/products'
      views: never
    }
    'resources/ts/pages/apps/invoice/create.vue': {
      routes: '/apps/invoice/create'
      views: never
    }
    'resources/ts/pages/apps/invoice/dashboard.vue': {
      routes: '/apps/invoice/dashboard'
      views: never
    }
    'resources/ts/pages/apps/invoice/details.vue': {
      routes: '/apps/invoice/details'
      views: never
    }
    'resources/ts/pages/apps/invoice/edit.vue': {
      routes: '/apps/invoice/edit'
      views: never
    }
    'resources/ts/pages/apps/invoice/list.vue': {
      routes: '/apps/invoice/list'
      views: never
    }
    'resources/ts/pages/apps/kanban.vue': {
      routes: '/apps/kanban'
      views: never
    }
    'resources/ts/pages/apps/mail.vue': {
      routes: '/apps/mail'
      views: never
    }
    'resources/ts/pages/apps/users/accountprofile/profile1.vue': {
      routes: '/apps/users/accountprofile/profile1'
      views: never
    }
    'resources/ts/pages/apps/users/accountprofile/profile2.vue': {
      routes: '/apps/users/accountprofile/profile2'
      views: never
    }
    'resources/ts/pages/apps/users/accountprofile/profile3.vue': {
      routes: '/apps/users/accountprofile/profile3'
      views: never
    }
    'resources/ts/pages/apps/users/card/card1.vue': {
      routes: '/apps/users/card/card1'
      views: never
    }
    'resources/ts/pages/apps/users/card/card2.vue': {
      routes: '/apps/users/card/card2'
      views: never
    }
    'resources/ts/pages/apps/users/card/card3.vue': {
      routes: '/apps/users/card/card3'
      views: never
    }
    'resources/ts/pages/apps/users/list/list1.vue': {
      routes: '/apps/users/list/list1'
      views: never
    }
    'resources/ts/pages/apps/users/list/list2.vue': {
      routes: '/apps/users/list/list2'
      views: never
    }
    'resources/ts/pages/apps/users/social/followers.vue': {
      routes: '/apps/users/social/followers'
      views: never
    }
    'resources/ts/pages/apps/users/social/friendrequest.vue': {
      routes: '/apps/users/social/friendrequest'
      views: never
    }
    'resources/ts/pages/apps/users/social/friends.vue': {
      routes: '/apps/users/social/friends'
      views: never
    }
    'resources/ts/pages/apps/users/social/gallery.vue': {
      routes: '/apps/users/social/gallery'
      views: never
    }
    'resources/ts/pages/apps/users/social/posts.vue': {
      routes: '/apps/users/social/posts'
      views: never
    }
    'resources/ts/pages/apps/users/userprofile.vue': {
      routes: '/apps/users/userprofile'
      views: never
    }
    'resources/ts/pages/authentication/auth1/CheckMail1.vue': {
      routes: '/authentication/auth1/CheckMail1'
      views: never
    }
    'resources/ts/pages/authentication/auth1/CodeVerification1.vue': {
      routes: '/authentication/auth1/CodeVerification1'
      views: never
    }
    'resources/ts/pages/authentication/auth1/ForgotPwd1.vue': {
      routes: '/authentication/auth1/ForgotPwd1'
      views: never
    }
    'resources/ts/pages/authentication/auth1/login1.vue': {
      routes: '/authentication/auth1/login1'
      views: never
    }
    'resources/ts/pages/authentication/auth1/register1.vue': {
      routes: '/authentication/auth1/register1'
      views: never
    }
    'resources/ts/pages/authentication/auth1/ResetPwd1.vue': {
      routes: '/authentication/auth1/ResetPwd1'
      views: never
    }
    'resources/ts/pages/authentication/auth2/CheckMail2.vue': {
      routes: '/authentication/auth2/CheckMail2'
      views: never
    }
    'resources/ts/pages/authentication/auth2/CodeVerification2.vue': {
      routes: '/authentication/auth2/CodeVerification2'
      views: never
    }
    'resources/ts/pages/authentication/auth2/ForgotPwd2.vue': {
      routes: '/authentication/auth2/ForgotPwd2'
      views: never
    }
    'resources/ts/pages/authentication/auth2/login2.vue': {
      routes: '/authentication/auth2/login2'
      views: never
    }
    'resources/ts/pages/authentication/auth2/register2.vue': {
      routes: '/authentication/auth2/register2'
      views: never
    }
    'resources/ts/pages/authentication/auth2/ResetPwd2.vue': {
      routes: '/authentication/auth2/ResetPwd2'
      views: never
    }
    'resources/ts/pages/authentication/auth3.vue': {
      routes: '/authentication/auth3'
      views: never
    }
    'resources/ts/pages/contactus.vue': {
      routes: '/contactus'
      views: never
    }
    'resources/ts/pages/dashboards/analytics.vue': {
      routes: '/dashboards/analytics'
      views: never
    }
    'resources/ts/pages/dashboards/default.vue': {
      routes: '/dashboards/default'
      views: never
    }
    'resources/ts/pages/documentos/index.vue': {
      routes: '/documentos/'
      views: never
    }
    'resources/ts/pages/documentos/atributos.vue': {
      routes: '/documentos/atributos'
      views: never
    }
    'resources/ts/pages/documentos/documentos.vue': {
      routes: '/documentos/documentos'
      views: never
    }
    'resources/ts/pages/documentos/layout.vue': {
      routes: '/documentos/layout'
      views: never
    }
    'resources/ts/pages/documentos/relatorio-layout.vue': {
      routes: '/documentos/relatorio-layout'
      views: never
    }
    'resources/ts/pages/documentos/relatorios.vue': {
      routes: '/documentos/relatorios'
      views: never
    }
    'resources/ts/pages/documentos/secoes.vue': {
      routes: '/documentos/secoes'
      views: never
    }
    'resources/ts/pages/documentos/tipos.vue': {
      routes: '/documentos/tipos'
      views: never
    }
    'resources/ts/pages/error500.vue': {
      routes: '/error500'
      views: never
    }
    'resources/ts/pages/faq.vue': {
      routes: '/faq'
      views: never
    }
    'resources/ts/pages/forms/charts/ApexChart.vue': {
      routes: '/forms/charts/ApexChart'
      views: never
    }
    'resources/ts/pages/forms/charts/orgchart.vue': {
      routes: '/forms/charts/orgchart'
      views: never
    }
    'resources/ts/pages/forms/components/autocomplete.vue': {
      routes: '/forms/components/autocomplete'
      views: never
    }
    'resources/ts/pages/forms/components/buttons.vue': {
      routes: '/forms/components/buttons'
      views: never
    }
    'resources/ts/pages/forms/components/checkbox.vue': {
      routes: '/forms/components/checkbox'
      views: never
    }
    'resources/ts/pages/forms/components/radio.vue': {
      routes: '/forms/components/radio'
      views: never
    }
    'resources/ts/pages/forms/components/slider.vue': {
      routes: '/forms/components/slider'
      views: never
    }
    'resources/ts/pages/forms/components/switch.vue': {
      routes: '/forms/components/switch'
      views: never
    }
    'resources/ts/pages/forms/components/textfield.vue': {
      routes: '/forms/components/textfield'
      views: never
    }
    'resources/ts/pages/forms/FormValidation.vue': {
      routes: '/forms/FormValidation'
      views: never
    }
    'resources/ts/pages/forms/layouts/ActionBar.vue': {
      routes: '/forms/layouts/ActionBar'
      views: never
    }
    'resources/ts/pages/forms/layouts/layouts.vue': {
      routes: '/forms/layouts/layouts'
      views: never
    }
    'resources/ts/pages/forms/layouts/MultiColumnForms.vue': {
      routes: '/forms/layouts/MultiColumnForms'
      views: never
    }
    'resources/ts/pages/forms/layouts/StickyActionBar.vue': {
      routes: '/forms/layouts/StickyActionBar'
      views: never
    }
    'resources/ts/pages/forms/plugins/captcha.vue': {
      routes: '/forms/plugins/captcha'
      views: never
    }
    'resources/ts/pages/forms/plugins/clipboard.vue': {
      routes: '/forms/plugins/clipboard'
      views: never
    }
    'resources/ts/pages/forms/plugins/dialog.vue': {
      routes: '/forms/plugins/dialog'
      views: never
    }
    'resources/ts/pages/forms/plugins/dropzone.vue': {
      routes: '/forms/plugins/dropzone'
      views: never
    }
    'resources/ts/pages/forms/plugins/editor.vue': {
      routes: '/forms/plugins/editor'
      views: never
    }
    'resources/ts/pages/forms/plugins/mask.vue': {
      routes: '/forms/plugins/mask'
      views: never
    }
    'resources/ts/pages/forms/plugins/tooltip.vue': {
      routes: '/forms/plugins/tooltip'
      views: never
    }
    'resources/ts/pages/forms/tables/TableBasic.vue': {
      routes: '/forms/tables/TableBasic'
      views: never
    }
    'resources/ts/pages/forms/tables/TableDark.vue': {
      routes: '/forms/tables/TableDark'
      views: never
    }
    'resources/ts/pages/forms/tables/TableDensity.vue': {
      routes: '/forms/tables/TableDensity'
      views: never
    }
    'resources/ts/pages/forms/tables/TableHeaderFixed.vue': {
      routes: '/forms/tables/TableHeaderFixed'
      views: never
    }
    'resources/ts/pages/forms/tables/TableHeight.vue': {
      routes: '/forms/tables/TableHeight'
      views: never
    }
    'resources/ts/pages/landing.vue': {
      routes: '/landing'
      views: never
    }
    'resources/ts/pages/maintenance/comingsoon1.vue': {
      routes: '/maintenance/comingsoon1'
      views: never
    }
    'resources/ts/pages/maintenance/comingsoon2.vue': {
      routes: '/maintenance/comingsoon2'
      views: never
    }
    'resources/ts/pages/pricing/pricing1.vue': {
      routes: '/pricing/pricing1'
      views: never
    }
    'resources/ts/pages/pricing/pricing2.vue': {
      routes: '/pricing/pricing2'
      views: never
    }
    'resources/ts/pages/privacypolicy.vue': {
      routes: '/privacypolicy'
      views: never
    }
    'resources/ts/pages/starter.vue': {
      routes: '/starter'
      views: never
    }
    'resources/ts/pages/ui-elements/advance/alert.vue': {
      routes: '/ui-elements/advance/alert'
      views: never
    }
    'resources/ts/pages/ui-elements/advance/buttontoggle.vue': {
      routes: '/ui-elements/advance/buttontoggle'
      views: never
    }
    'resources/ts/pages/ui-elements/advance/emptystate.vue': {
      routes: '/ui-elements/advance/emptystate'
      views: never
    }
    'resources/ts/pages/ui-elements/advance/floatingaction.vue': {
      routes: '/ui-elements/advance/floatingaction'
      views: never
    }
    'resources/ts/pages/ui-elements/advance/pagination.vue': {
      routes: '/ui-elements/advance/pagination'
      views: never
    }
    'resources/ts/pages/ui-elements/advance/progress.vue': {
      routes: '/ui-elements/advance/progress'
      views: never
    }
    'resources/ts/pages/ui-elements/advance/ratings.vue': {
      routes: '/ui-elements/advance/ratings'
      views: never
    }
    'resources/ts/pages/ui-elements/advance/snackbar.vue': {
      routes: '/ui-elements/advance/snackbar'
      views: never
    }
    'resources/ts/pages/ui-elements/advance/speeddial.vue': {
      routes: '/ui-elements/advance/speeddial'
      views: never
    }
    'resources/ts/pages/ui-elements/advance/timeline.vue': {
      routes: '/ui-elements/advance/timeline'
      views: never
    }
    'resources/ts/pages/ui-elements/basic/avatar.vue': {
      routes: '/ui-elements/basic/avatar'
      views: never
    }
    'resources/ts/pages/ui-elements/basic/badges.vue': {
      routes: '/ui-elements/basic/badges'
      views: never
    }
    'resources/ts/pages/ui-elements/basic/breadcrumb.vue': {
      routes: '/ui-elements/basic/breadcrumb'
      views: never
    }
    'resources/ts/pages/ui-elements/basic/cards.vue': {
      routes: '/ui-elements/basic/cards'
      views: never
    }
    'resources/ts/pages/ui-elements/basic/chip.vue': {
      routes: '/ui-elements/basic/chip'
      views: never
    }
    'resources/ts/pages/ui-elements/basic/expansionpanel.vue': {
      routes: '/ui-elements/basic/expansionpanel'
      views: never
    }
    'resources/ts/pages/ui-elements/basic/tabs.vue': {
      routes: '/ui-elements/basic/tabs'
      views: never
    }
    'resources/ts/pages/ui-elements/basic/UiList.vue': {
      routes: '/ui-elements/basic/UiList'
      views: never
    }
    'resources/ts/pages/underconstruction/construction1.vue': {
      routes: '/underconstruction/construction1'
      views: never
    }
    'resources/ts/pages/underconstruction/construction2.vue': {
      routes: '/underconstruction/construction2'
      views: never
    }
    'resources/ts/pages/utilities/animation.vue': {
      routes: '/utilities/animation'
      views: never
    }
    'resources/ts/pages/utilities/colors.vue': {
      routes: '/utilities/colors'
      views: never
    }
    'resources/ts/pages/utilities/grid.vue': {
      routes: '/utilities/grid'
      views: never
    }
    'resources/ts/pages/utilities/icons/material.vue': {
      routes: '/utilities/icons/material'
      views: never
    }
    'resources/ts/pages/utilities/icons/tabler.vue': {
      routes: '/utilities/icons/tabler'
      views: never
    }
    'resources/ts/pages/utilities/shadows.vue': {
      routes: '/utilities/shadows'
      views: never
    }
    'resources/ts/pages/utilities/typography.vue': {
      routes: '/utilities/typography'
      views: never
    }
    'resources/ts/pages/widgets/chart.vue': {
      routes: '/widgets/chart'
      views: never
    }
    'resources/ts/pages/widgets/data.vue': {
      routes: '/widgets/data'
      views: never
    }
    'resources/ts/pages/widgets/statistics.vue': {
      routes: '/widgets/statistics'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
