const STORAGE_KEY = 'documentos_app_v2';
const DOCUMENTO_API_URL = String((window as any).DOCUMENTO_API_URL || '').trim();

const state: AppState = loadState();
const ui = {
  // tipos
  tipoForm: document.getElementById('tipoForm'),
  tipoId: document.getElementById('tipoId'),
  tipoNome: document.getElementById('tipoNome'),
  tipoCabecalho: document.getElementById('tipoCabecalho'),
  tipoRodape: document.getElementById('tipoRodape'),
  tipoCancelBtn: document.getElementById('tipoCancelBtn'),
  tipoOpenModalBtn: document.getElementById('tipoOpenModalBtn'),
  tipoModal: document.getElementById('tipoModal'),
  tipoSecoesWrap: document.getElementById('tipoSecoesWrap'),
  tipoSecoesList: document.getElementById('tipoSecoesList'),
  tiposList: document.getElementById('tiposList'),

  // secoes
  secaoForm: document.getElementById('secaoForm'),
  secaoId: document.getElementById('secaoId'),
  secaoNome: document.getElementById('secaoNome'),
  secaoCabecalho: document.getElementById('secaoCabecalho'),
  secaoRodape: document.getElementById('secaoRodape'),
  secaoCancelBtn: document.getElementById('secaoCancelBtn'),
  secaoOpenModalBtn: document.getElementById('secaoOpenModalBtn'),
  secaoModal: document.getElementById('secaoModal'),
  secoesList: document.getElementById('secoesList'),

  // atributos
  atributoForm: document.getElementById('atributoForm'),
  atributoId: document.getElementById('atributoId'),
  atributoTipo: document.getElementById('atributoTipo'),
  atributoNome: document.getElementById('atributoNome'),
  atributoTipoCampo: document.getElementById('atributoTipoCampo'),
  atributoTemplateWrap: document.getElementById('atributoTemplateWrap'),
  atributoTemplateTexto: document.getElementById('atributoTemplateTexto'),
  atributoSecao: document.getElementById('atributoSecao'),
  atributoValidador: document.getElementById('atributoValidador'),
  atributoPeso: document.getElementById('atributoPeso'),
  atributoMascara: document.getElementById('atributoMascara'),
  atributoCancelBtn: document.getElementById('atributoCancelBtn'),
  atributoOpenModalBtn: document.getElementById('atributoOpenModalBtn'),
  atributoModal: document.getElementById('atributoModal'),
  atributosList: document.getElementById('atributosList'),

  // layout
  layoutTipo: document.getElementById('layoutTipo'),
  layoutSaveBtn: document.getElementById('layoutSaveBtn'),
  layoutResetBtn: document.getElementById('layoutResetBtn'),
  layoutGridEditor: document.getElementById('layoutGridEditor'),

  // documentos
  documentoForm: document.getElementById('documentoForm'),
  documentoId: document.getElementById('documentoId'),
  documentoTitulo: document.getElementById('documentoTitulo'),
  documentoTipo: document.getElementById('documentoTipo'),
  documentoCampos: document.getElementById('documentoCampos'),
  documentoCancelBtn: document.getElementById('documentoCancelBtn'),
  documentoOpenModalBtn: document.getElementById('documentoOpenModalBtn'),
  documentoModal: document.getElementById('documentoModal'),
  documentosList: document.getElementById('documentosList'),

  // relatorios
  relatorioTipo: document.getElementById('relatorioTipo'),
  relatorioConfigNome: document.getElementById('relatorioConfigNome'),
  relatorioConfigSelect: document.getElementById('relatorioConfigSelect'),
  relatorioSalvarConfigBtn: document.getElementById('relatorioSalvarConfigBtn'),
  relatorioSelecionarConfigBtn: document.getElementById('relatorioSelecionarConfigBtn'),
  relatorioExportConfigBtn: document.getElementById('relatorioExportConfigBtn'),
  relatorioConfigDialog: document.getElementById('relatorioConfigDialog'),
  relatorioConfigList: document.getElementById('relatorioConfigList'),
  relatorioDialogCloseBtn: document.getElementById('relatorioDialogCloseBtn'),
  relatorioAtributosWrap: document.getElementById('relatorioAtributosWrap'),
  relatorioFiltroAtributo: document.getElementById('relatorioFiltroAtributo'),
  relatorioFiltroOperador: document.getElementById('relatorioFiltroOperador'),
  relatorioFiltroValor: document.getElementById('relatorioFiltroValor'),
  relatorioOrdenarAtributo: document.getElementById('relatorioOrdenarAtributo'),
  relatorioOrdenarDirecao: document.getElementById('relatorioOrdenarDirecao'),
  relatorioOrdenarAdicionarBtn: document.getElementById('relatorioOrdenarAdicionarBtn'),
  relatorioOrdenacaoLista: document.getElementById('relatorioOrdenacaoLista'),
  relatorioLayoutEditor: document.getElementById('relatorioLayoutEditor'),
  relatorioSalvarLayoutBtn: document.getElementById('relatorioSalvarLayoutBtn'),
  relatorioGerarBtn: document.getElementById('relatorioGerarBtn'),
  relatorioCsvBtn: document.getElementById('relatorioCsvBtn'),
  relatorioPdfBtn: document.getElementById('relatorioPdfBtn'),
  relatorioSomarNumeros: document.getElementById('relatorioSomarNumeros'),
  relatorioResumo: document.getElementById('relatorioResumo'),
  relatorioTabela: document.getElementById('relatorioTabela'),
  relatorioTabelaHead: document.getElementById('relatorioTabelaHead'),
  relatorioTabelaBody: document.getElementById('relatorioTabelaBody'),

  // layout de relatorio (pagina separada)
  relatorioLayoutTipo: document.getElementById('relatorioLayoutTipo'),
  relatorioLayoutConfig: document.getElementById('relatorioLayoutConfig'),
  relatorioLayoutAddSpacerBtn: document.getElementById('relatorioLayoutAddSpacerBtn'),
  relatorioLayoutSaveBtn: document.getElementById('relatorioLayoutSaveBtn'),
  relatorioLayoutResetBtn: document.getElementById('relatorioLayoutResetBtn'),
  relatorioLayoutCanvas: document.getElementById('relatorioLayoutCanvas'),
  relatorioLayoutBlockCanvas: document.getElementById('relatorioLayoutBlockCanvas'),
  relatorioLayoutFooterMode: document.getElementById('relatorioLayoutFooterMode'),
  relatorioLayoutFooterAnchor: document.getElementById('relatorioLayoutFooterAnchor'),
} as Record<string, any>;
